require("prototypes.tiles")
require("prototypes.item")
require("prototypes.equipment")
require("prototypes.recipe")
require("prototypes.technologies")
require("prototypes.item-groups")
require("prototypes.vehicles")
require("prototypes.entities")
